version: "2"
services:
  api:
    build: .
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/api
    ports:
      - "8042:8080"
    depends_on:
      - db
    links:
      - db
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "db"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
